begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_net;
create extension if not exists pg_cron;
create extension if not exists supabase_vault with schema vault;

create schema if not exists app;
revoke all on schema app from public, anon, authenticated;

create table app.settings (
  id bigint primary key default 1 check (id = 1),
  custom_prompt text,
  version integer not null default 1 check (version > 0),
  profile_invalidated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table app.linkedin_tokens (
  id bigint generated by default as identity primary key,
  access_token_cipher jsonb not null,
  refresh_token_cipher jsonb,
  cipher_version smallint not null default 1 check (cipher_version = 1),
  person_urn text not null,
  person_name text not null default '',
  person_picture text not null default '',
  expires_at timestamptz,
  refresh_token_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(access_token_cipher) = 'object'),
  check (refresh_token_cipher is null or jsonb_typeof(refresh_token_cipher) = 'object')
);

create table app.posts (
  id bigint generated by default as identity primary key,
  tweet_url text not null,
  tweet_text text not null default '',
  tweet_author text not null default '',
  linkedin_text text not null default '',
  image_urls jsonb not null default '[]'::jsonb check (jsonb_typeof(image_urls) = 'array'),
  scheduled_at timestamptz,
  approved_at timestamptz,
  publish_at timestamptz,
  publishing_at timestamptz,
  published_at timestamptz,
  status text not null default 'pending' check (
    status in (
      'pending', 'radar_slot', 'approval_pending', 'scheduled', 'publishing',
      'published', 'failed', 'cancelled', 'paused'
    )
  ),
  linkedin_post_id text,
  request_fingerprint text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  use_first_image boolean not null default false,
  media_type text not null default 'none' check (
    media_type in ('none', 'image', 'video', 'document', 'paper_image', 'auto')
  ),
  pdf_url text,
  document_title text not null default 'Documento',
  source text not null default 'manual',
  manual_edited_at timestamptz,
  manual_edited_via text,
  editorial_revision_notes text,
  generated_image_path text,
  li_likes integer check (li_likes is null or li_likes >= 0),
  li_comments integer check (li_comments is null or li_comments >= 0),
  li_impressions integer check (li_impressions is null or li_impressions >= 0),
  li_clicks integer check (li_clicks is null or li_clicks >= 0),
  li_shares integer check (li_shares is null or li_shares >= 0),
  metrics_updated_at timestamptz,
  source_metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(source_metadata) = 'object'),
  verification_metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(verification_metadata) = 'object'),
  version integer not null default 1 check (version > 0),
  check (status <> 'published' or published_at is not null),
  check (status not in ('scheduled', 'publishing') or publish_at is not null)
);

create unique index posts_linkedin_post_id_unique
  on app.posts (linkedin_post_id)
  where linkedin_post_id is not null and linkedin_post_id <> '';
create index posts_status_publish_at_idx on app.posts (status, publish_at);
create index posts_source_status_idx on app.posts (source, status);
create index posts_published_at_idx on app.posts (published_at desc);
create index posts_scheduled_at_idx on app.posts (scheduled_at);
create unique index posts_radar_slot_url_unique on app.posts (tweet_url)
  where source = 'radar' and tweet_url like 'radar://slot/%';

create table app.x_liked_tweets (
  id bigint generated by default as identity primary key,
  tweet_id text not null unique,
  tweet_url text not null,
  tweet_author text not null default '',
  processed_at timestamptz not null default now(),
  post_id bigint references app.posts(id) on delete set null,
  status text not null default 'processing',
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table app.linkedin_comments (
  id bigint generated by default as identity primary key,
  scheduled_post_id bigint references app.posts(id) on delete set null,
  linkedin_post_urn text not null,
  linkedin_object_urn text not null default '',
  linkedin_comment_urn text not null unique,
  parent_comment_urn text,
  commenter_name text not null default '',
  commenter_profile_url text not null default '',
  commenter_headline text not null default '',
  comment_text text not null,
  comment_age_label text not null default '',
  post_public_url text not null default '',
  suggested_reply text,
  reply_status text not null default 'pending',
  telegram_message_id bigint,
  last_notified_at timestamptz,
  owner_replied boolean not null default false,
  owner_reply_text text,
  published_reply_urn text,
  published_reply_text text,
  error_message text,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index linkedin_comments_post_idx on app.linkedin_comments (scheduled_post_id);
create index linkedin_comments_reply_status_idx on app.linkedin_comments (reply_status, created_at);

create table app.job_queue (
  id bigint generated by default as identity primary key,
  job_type text not null,
  run_at timestamptz not null,
  status text not null default 'pending' check (
    status in ('pending', 'claimed', 'running', 'succeeded', 'retry_wait', 'dead', 'cancelled')
  ),
  priority integer not null default 100,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  result jsonb not null default '{}'::jsonb check (jsonb_typeof(result) = 'object'),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 5 check (max_attempts between 1 and 20),
  lease_owner text,
  lease_token uuid,
  leased_until timestamptz,
  dedupe_key text not null unique,
  correlation_id uuid,
  last_error text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index job_queue_due_idx on app.job_queue (status, run_at, priority, id);
create index job_queue_lease_idx on app.job_queue (leased_until)
  where status in ('claimed', 'running');

create table app.external_effects (
  id bigint generated by default as identity primary key,
  effect_type text not null,
  idempotency_key text not null unique,
  entity_type text not null,
  entity_id text not null,
  request_fingerprint text not null,
  request_payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (
    status in ('pending', 'executing', 'succeeded', 'ambiguous', 'failed', 'cancelled')
  ),
  lease_token uuid,
  leased_until timestamptz,
  external_id text,
  response_payload jsonb,
  last_error text,
  attempts integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);
create index external_effects_status_idx on app.external_effects (status, created_at);

create table app.publication_attempts (
  id bigint generated by default as identity primary key,
  post_id bigint not null references app.posts(id) on delete cascade,
  effect_id bigint not null references app.external_effects(id) on delete restrict,
  attempt_number integer not null check (attempt_number > 0),
  request_fingerprint text not null,
  status text not null,
  linkedin_post_id text,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (post_id, attempt_number)
);

create table app.telegram_updates (
  update_id bigint primary key,
  chat_id bigint,
  user_id bigint,
  update_type text not null,
  payload_hash text not null,
  status text not null default 'received' check (
    status in ('received', 'processed', 'rejected', 'failed')
  ),
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create table app.telegram_messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  message_id bigint not null,
  post_id bigint references app.posts(id) on delete set null,
  comment_id bigint references app.linkedin_comments(id) on delete set null,
  message_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (chat_id, message_id)
);
create index telegram_messages_post_idx on app.telegram_messages (post_id, created_at desc);

create table app.telegram_sessions (
  user_id bigint primary key,
  chat_id bigint not null,
  mode text not null,
  post_id bigint references app.posts(id) on delete cascade,
  comment_id bigint references app.linkedin_comments(id) on delete cascade,
  draft jsonb not null default '{}'::jsonb,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table app.radar_candidates (
  id bigint generated by default as identity primary key,
  post_id bigint references app.posts(id) on delete cascade,
  source_url text not null,
  normalized_url text not null,
  title text not null,
  summary text not null default '',
  source_name text not null default '',
  source_domain text not null,
  source_kind text not null,
  published_at timestamptz,
  discovered_at timestamptz not null default now(),
  score numeric(12,4) not null default 0,
  rank integer,
  decision_reason text,
  intent text,
  angle text,
  selected boolean not null default false,
  excluded boolean not null default false,
  exclusion_reason text,
  raw_metadata jsonb not null default '{}'::jsonb,
  unique (post_id, normalized_url)
);
create index radar_candidates_normalized_url_idx on app.radar_candidates (normalized_url);
create index radar_candidates_post_rank_idx on app.radar_candidates (post_id, rank);

create table app.editorial_profiles (
  id bigint generated by default as identity primary key,
  version integer not null unique,
  profile_text text not null,
  sample_post_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(sample_post_ids) = 'array'),
  strong_post_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(strong_post_ids) = 'array'),
  weak_post_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(weak_post_ids) = 'array'),
  metrics_fingerprint text not null,
  generated_by text not null,
  created_at timestamptz not null default now()
);

create table app.oauth_states (
  state_hash bytea primary key,
  provider text not null,
  redirect_after text not null default '/',
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index oauth_states_expiry_idx on app.oauth_states (expires_at);

create table app.event_log (
  id bigint generated by default as identity primary key,
  subsystem text not null,
  event_type text not null,
  severity text not null default 'info' check (
    severity in ('debug', 'info', 'warning', 'error', 'critical')
  ),
  correlation_id uuid,
  entity_type text,
  entity_id text,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  dedupe_key text,
  created_at timestamptz not null default now()
);
create unique index event_log_dedupe_unique on app.event_log (dedupe_key)
  where dedupe_key is not null;
create index event_log_subsystem_created_idx on app.event_log (subsystem, created_at desc);

create table app.system_health (
  subsystem text primary key,
  last_success_at timestamptz,
  last_error_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table app.periodic_cursors (
  job_type text primary key,
  cursor_value jsonb not null default '{}'::jsonb,
  last_run_at timestamptz,
  last_success_at timestamptz,
  updated_at timestamptz not null default now()
);

create table app.backup_runs (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('started', 'succeeded', 'failed', 'restore_verified')),
  artifact_name text,
  size_bytes bigint,
  checksum text,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table app.cost_usage (
  id bigint generated by default as identity primary key,
  function_name text not null,
  duration_ms bigint not null default 0,
  request_count integer not null default 1,
  production_deploys integer not null default 0,
  estimated_credits numeric(14,6) not null default 0,
  correlation_id uuid,
  occurred_at timestamptz not null default now()
);
create index cost_usage_month_idx on app.cost_usage (occurred_at);

create table app.rate_limits (
  bucket_key text primary key,
  window_started_at timestamptz not null,
  request_count integer not null,
  updated_at timestamptz not null default now()
);

create table app.import_runs (
  id bigint generated by default as identity primary key,
  manifest_hash text not null unique,
  source_database_hash text not null,
  status text not null check (status in ('started', 'succeeded', 'failed')),
  counts jsonb not null default '{}'::jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create or replace function app.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger settings_updated_at before update on app.settings
  for each row execute function app.set_updated_at();
create trigger linkedin_tokens_updated_at before update on app.linkedin_tokens
  for each row execute function app.set_updated_at();
create trigger posts_updated_at before update on app.posts
  for each row execute function app.set_updated_at();
create trigger x_liked_tweets_updated_at before update on app.x_liked_tweets
  for each row execute function app.set_updated_at();
create trigger linkedin_comments_updated_at before update on app.linkedin_comments
  for each row execute function app.set_updated_at();
create trigger job_queue_updated_at before update on app.job_queue
  for each row execute function app.set_updated_at();
create trigger external_effects_updated_at before update on app.external_effects
  for each row execute function app.set_updated_at();
create trigger telegram_sessions_updated_at before update on app.telegram_sessions
  for each row execute function app.set_updated_at();
create trigger system_health_updated_at before update on app.system_health
  for each row execute function app.set_updated_at();
create trigger periodic_cursors_updated_at before update on app.periodic_cursors
  for each row execute function app.set_updated_at();
create trigger rate_limits_updated_at before update on app.rate_limits
  for each row execute function app.set_updated_at();

create or replace function app.enqueue_job(
  p_job_type text,
  p_run_at timestamptz,
  p_payload jsonb,
  p_dedupe_key text,
  p_max_attempts integer default 5,
  p_priority integer default 100,
  p_correlation_id uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = app, extensions, pg_catalog
as $$
declare
  v_id bigint;
begin
  insert into app.job_queue (
    job_type, run_at, payload, dedupe_key, max_attempts, priority, correlation_id
  ) values (
    p_job_type, p_run_at, coalesce(p_payload, '{}'::jsonb), p_dedupe_key,
    greatest(1, least(p_max_attempts, 20)), p_priority, p_correlation_id
  )
  on conflict (dedupe_key) do update
    set updated_at = now()
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function app.approve_post(
  p_post_id bigint,
  p_actor text default 'telegram'
)
returns table (
  post_id bigint,
  status text,
  publish_at timestamptz,
  job_id bigint,
  already_processed boolean
)
language plpgsql
security definer
set search_path = app, extensions, pg_catalog
as $$
declare
  v_post app.posts%rowtype;
  v_now timestamptz := clock_timestamp();
  v_publish_at timestamptz;
  v_job_id bigint;
begin
  select * into v_post from app.posts where id = p_post_id for update;
  if not found then
    raise exception 'post_not_found' using errcode = 'P0002';
  end if;

  if v_post.status in ('scheduled', 'publishing', 'published') and v_post.approved_at is not null then
    select id into v_job_id
    from app.job_queue
    where dedupe_key = 'publish_post:' || p_post_id::text;
    return query select v_post.id, v_post.status, v_post.publish_at, v_job_id, true;
    return;
  end if;

  if v_post.status <> 'approval_pending' then
    raise exception 'post_not_approval_pending' using errcode = 'P0001';
  end if;

  v_publish_at := v_now + interval '30 minutes';
  update app.posts
  set
    approved_at = v_now,
    publish_at = v_publish_at,
    scheduled_at = v_publish_at,
    status = 'scheduled',
    media_type = case when media_type = 'auto' then 'none' else media_type end,
    generated_image_path = null,
    manual_edited_at = v_now,
    manual_edited_via = coalesce(manual_edited_via, p_actor),
    error_message = null,
    version = version + 1
  where id = p_post_id
  returning * into v_post;

  v_job_id := app.enqueue_job(
    'publish_post',
    v_publish_at,
    jsonb_build_object('post_id', p_post_id),
    'publish_post:' || p_post_id::text,
    5,
    10,
    null
  );
  return query select v_post.id, v_post.status, v_post.publish_at, v_job_id, false;
end;
$$;

create or replace function app.cancel_post(
  p_post_id bigint,
  p_actor text default 'dashboard'
)
returns text
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
declare
  v_status text;
begin
  select status into v_status from app.posts where id = p_post_id for update;
  if not found then
    raise exception 'post_not_found' using errcode = 'P0002';
  end if;
  if v_status not in ('pending', 'radar_slot', 'approval_pending', 'scheduled', 'failed') then
    return v_status;
  end if;
  update app.posts
  set status = 'cancelled',
      error_message = 'Cancelled by ' || p_actor,
      version = version + 1
  where id = p_post_id;
  update app.job_queue
  set status = 'cancelled', completed_at = now()
  where status in ('pending', 'retry_wait', 'claimed')
    and payload @> jsonb_build_object('post_id', p_post_id);
  return 'cancelled';
end;
$$;

create or replace function app.append_revision_and_enqueue(
  p_post_id bigint,
  p_instruction text,
  p_actor text default 'telegram'
)
returns bigint
language plpgsql
security definer
set search_path = app, extensions, pg_catalog
as $$
declare
  v_notes text;
  v_version integer;
  v_job_id bigint;
  v_instruction text := btrim(p_instruction);
begin
  if v_instruction = '' or length(v_instruction) > 5000 then
    raise exception 'invalid_revision_instruction' using errcode = '22023';
  end if;

  select editorial_revision_notes, version
  into v_notes, v_version
  from app.posts
  where id = p_post_id and status = 'approval_pending'
  for update;
  if not found then
    raise exception 'post_not_approval_pending' using errcode = 'P0002';
  end if;

  if not exists (
    select 1
    from unnest(string_to_array(coalesce(v_notes, ''), E'\n')) as note
    where lower(btrim(note)) = lower(v_instruction)
  ) then
    v_notes := left(concat_ws(E'\n', nullif(v_notes, ''), v_instruction), 5000);
  end if;

  update app.posts
  set editorial_revision_notes = v_notes,
      manual_edited_at = now(),
      manual_edited_via = p_actor,
      version = version + 1
  where id = p_post_id
  returning version into v_version;

  v_job_id := app.enqueue_job(
    'revise_post',
    now(),
    jsonb_build_object('post_id', p_post_id),
    'revise_post:' || p_post_id::text || ':' || v_version::text,
    4,
    30,
    null
  );
  return v_job_id;
end;
$$;

create or replace function app.claim_due_jobs(
  p_worker_id text,
  p_limit integer default 5,
  p_lease_seconds integer default 900
)
returns table (
  id bigint,
  job_type text,
  payload jsonb,
  attempts integer,
  max_attempts integer,
  lease_token uuid,
  correlation_id uuid
)
language sql
security definer
set search_path = app, extensions, pg_catalog
as $$
  with due as (
    select q.id
    from app.job_queue q
    where q.status in ('pending', 'retry_wait')
      and q.run_at <= now()
    order by q.priority asc, q.run_at asc, q.id asc
    for update skip locked
    limit greatest(1, least(p_limit, 20))
  ),
  claimed as (
    update app.job_queue q
    set status = 'claimed',
        attempts = q.attempts + 1,
        lease_owner = p_worker_id,
        lease_token = extensions.gen_random_uuid(),
        leased_until = now() + make_interval(secs => greatest(30, least(p_lease_seconds, 900))),
        last_error = null
    from due
    where q.id = due.id
    returning q.id, q.job_type, q.payload, q.attempts, q.max_attempts,
              q.lease_token, q.correlation_id
  )
  select * from claimed;
$$;

create or replace function app.start_job(p_job_id bigint, p_lease_token uuid)
returns boolean
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
begin
  update app.job_queue
  set status = 'running', started_at = coalesce(started_at, now())
  where id = p_job_id
    and status = 'claimed'
    and lease_token = p_lease_token
    and leased_until > now();
  return found;
end;
$$;

create or replace function app.complete_job(
  p_job_id bigint,
  p_lease_token uuid,
  p_result jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
begin
  update app.job_queue
  set status = 'succeeded',
      result = coalesce(p_result, '{}'::jsonb),
      completed_at = now(),
      leased_until = null,
      lease_owner = null
  where id = p_job_id
    and status in ('claimed', 'running')
    and lease_token = p_lease_token;
  return found;
end;
$$;

create or replace function app.fail_job(
  p_job_id bigint,
  p_lease_token uuid,
  p_error text
)
returns text
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
declare
  v_attempts integer;
  v_max_attempts integer;
  v_status text;
begin
  select attempts, max_attempts
  into v_attempts, v_max_attempts
  from app.job_queue
  where id = p_job_id
    and lease_token = p_lease_token
    and status in ('claimed', 'running')
  for update;
  if not found then
    return 'dead';
  end if;

  v_status := case when v_attempts >= v_max_attempts then 'dead' else 'retry_wait' end;
  update app.job_queue
  set status = v_status,
      run_at = case
        when v_status = 'retry_wait'
          then now() + make_interval(secs => least(3600, 60 * power(2, greatest(v_attempts - 1, 0))::integer))
        else run_at
      end,
      last_error = left(p_error, 2000),
      completed_at = case when v_status = 'dead' then now() else null end,
      leased_until = null,
      lease_owner = null
  where id = p_job_id;
  return v_status;
end;
$$;

create or replace function app.recover_expired_leases()
returns integer
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
declare
  v_count integer;
begin
  update app.job_queue
  set status = case when attempts >= max_attempts then 'dead' else 'retry_wait' end,
      run_at = now(),
      last_error = 'Lease expired',
      leased_until = null,
      lease_owner = null,
      completed_at = case when attempts >= max_attempts then now() else null end
  where status in ('claimed', 'running')
    and leased_until <= now();
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function app.claim_post_for_publication(
  p_post_id bigint,
  p_fingerprint text
)
returns boolean
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
begin
  update app.posts
  set status = 'publishing',
      publishing_at = now(),
      request_fingerprint = p_fingerprint,
      error_message = null
  where id = p_post_id
    and status = 'scheduled'
    and publish_at <= now();
  return found;
end;
$$;

create or replace function app.mark_post_published(
  p_post_id bigint,
  p_linkedin_post_id text
)
returns boolean
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
begin
  update app.posts
  set status = 'published',
      linkedin_post_id = p_linkedin_post_id,
      published_at = now(),
      error_message = null
  where id = p_post_id and status = 'publishing';
  return found;
end;
$$;

create or replace function app.consume_rate_limit(
  p_bucket_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
declare
  v_count integer;
begin
  insert into app.rate_limits (bucket_key, window_started_at, request_count)
  values (p_bucket_key, now(), 1)
  on conflict (bucket_key) do update
    set window_started_at = case
          when app.rate_limits.window_started_at + make_interval(secs => p_window_seconds) <= now()
            then now()
          else app.rate_limits.window_started_at
        end,
        request_count = case
          when app.rate_limits.window_started_at + make_interval(secs => p_window_seconds) <= now()
            then 1
          else app.rate_limits.request_count + 1
        end
  returning request_count into v_count;
  return v_count <= p_limit;
end;
$$;

create or replace function app.schedule_periodic_jobs()
returns integer
language plpgsql
security definer
set search_path = app, pg_catalog
as $$
declare
  v_count integer := 0;
  v_id bigint;
  v_hour text := to_char(date_trunc('hour', now()), 'YYYYMMDDHH24');
  v_radar_bucket text :=
    to_char(date_trunc('day', now()), 'YYYYMMDD') || ':' ||
    floor(extract(hour from now()) / 6)::integer::text;
  v_cost_bucket text :=
    to_char(date_trunc('day', now()), 'YYYYMMDD') || ':' ||
    floor(extract(hour from now()) / 6)::integer::text;
begin
  v_id := app.enqueue_job(
    'comments_sync',
    now(),
    '{}'::jsonb,
    'comments_sync:' || v_hour,
    4,
    70,
    null
  );
  v_count := v_count + 1;

  v_id := app.enqueue_job(
    'cost_monitor',
    now(),
    '{}'::jsonb,
    'cost_monitor:' || v_cost_bucket,
    4,
    90,
    null
  );
  v_count := v_count + 1;

  v_id := app.enqueue_job(
    'radar_maintenance',
    now(),
    '{}'::jsonb,
    'radar_maintenance:' || v_radar_bucket,
    4,
    50,
    null
  );
  v_count := v_count + 1;

  v_id := app.enqueue_job(
    'metrics_refresh',
    now(),
    '{}'::jsonb,
    'metrics_refresh:' || to_char(now(), 'YYYYMMDD'),
    4,
    80,
    null
  );
  v_count := v_count + 1;
  return v_count;
end;
$$;

create or replace function app.dispatch_due_jobs()
returns bigint
language plpgsql
security definer
set search_path = app, vault, net, pg_catalog
as $$
declare
  v_due bigint;
  v_url text;
  v_secret text;
begin
  perform app.recover_expired_leases();
  perform app.schedule_periodic_jobs();

  select count(*) into v_due
  from app.job_queue
  where status in ('pending', 'retry_wait') and run_at <= now();
  if v_due = 0 then
    return 0;
  end if;

  select decrypted_secret into v_url
  from vault.decrypted_secrets where name = 'x2li_dispatch_url' limit 1;
  select decrypted_secret into v_secret
  from vault.decrypted_secrets where name = 'x2li_dispatch_secret' limit 1;
  if v_url is null or v_secret is null then
    raise exception 'dispatch_vault_secrets_missing';
  end if;

  perform net.http_post(
    url := v_url,
    headers := jsonb_build_object(
      'content-type', 'application/json',
      'x-dispatch-secret', v_secret
    ),
    body := jsonb_build_object('source', 'supabase_cron', 'due', v_due),
    timeout_milliseconds := 5000
  );
  return v_due;
end;
$$;

insert into app.settings (id) values (1) on conflict do nothing;
insert into app.system_health (subsystem)
values
  ('database'), ('telegram'), ('linkedin'), ('radar'), ('queue'), ('backup'), ('cost')
on conflict do nothing;

revoke all on all tables in schema app from public, anon, authenticated;
revoke all on all sequences in schema app from public, anon, authenticated;
revoke all on all functions in schema app from public, anon, authenticated;
alter default privileges in schema app revoke all on tables from public, anon, authenticated;
alter default privileges in schema app revoke all on sequences from public, anon, authenticated;
alter default privileges in schema app revoke all on functions from public, anon, authenticated;

commit;
